version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: teste_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3336:3306"
    expose:
      - "3336"
    volumes:
      - my-db:/var/lib/mysql
  server:
      build:
        context: .
        dockerfile: Dockerfile
      env_file: .env
      depends_on:
        - database
      networks:
        - default
      ports:
        - 8081:8081
volumes:
  my-db: